API:
  app_name: demo
  host: 0.0.0.0 # DO NOT change, except only data from specific host needs to be listen
  port: 8888
datasource:
  host: localhost
  port: 0
  user: IRDBA
  password: complexpwd
  database_name: ir
  test_database_name: ir_test1
  pool_size: 5
  max_overflow: 10
  timeout: 60
  rebuild: False
spark:
  master: local
  app_name: ir
  spark.executorEnv.PYTHONHASHSEED: 0
sorter:
  bm25:
    k: 1.5
    b: 0.75
    title_bias: 2
functions:
  autocomplete:
    default_number: 3
  similar_search:
    candidate_number: 2
    candidate_replace_times: 1
    candidate_length: 3
    default_number: 3
  snippet:
    max_length: 50 # 字数
  emotions:
    port: 8090 # restful API地址，当然也可以直接请求这个地址。
    host: localhost
indexes:
  word_synonym:
    model_cache_path: models/word_synonyms
    default_number: 3
  word_text:
    similar:
      default_threshold: 1
      penalties: [1, 1, 1] # add, del, rep
  word_cooccurrence:
    model_cache_path: models/word_cooccurrence
cache:
  redis_host: localhost
  redis_port: 6379
  expire_delta: 7200
