API:
  app_name: demo
  host: 0.0.0.0 # DO NOT change, except only data from specific host needs to be listen
  port: 8888
datasource:
  host: localhost
  port: 0
  user: IRDBA
  password: complexpwd
  database_name: ir
  test_database_name: ir_test
  pool_size: 5
  max_overflow: 10
  timeout: 60
  rebuild: True
spark:
  master: local
  app_name: ir
sorter:
  bm25:
    k: 1.5
    b: 0.75
    title_bias: 2
functions:
  autocomplete:
    default_number: 3
indexes:
  word_synonym:
    model_cache_path: models/word_synonyms.cache
    default_number: 3